const ADMIN_PRODUIT_PRODUIT = "ADMIN_PRODUIT_PRODUIT";
const ADMIN_PRODUIT_CATEGORIE = "ADMIN_PRODUIT_CATEGORIE";

const ADMIN_PRODUIT_LOCALSTORAGE = "ADMIN_PRODUIT_LOCALSTORAGE";

export {
    ADMIN_PRODUIT_PRODUIT,
    ADMIN_PRODUIT_CATEGORIE
}

export function getADMIN_PRODUIT_LOCALSTORAGE() {
    return localStorage.getItem(ADMIN_PRODUIT_LOCALSTORAGE) || ADMIN_PRODUIT_PRODUIT;
}

export function setADMIN_PRODUIT_LOCALSTORAGE(value) {
    localStorage.setItem(ADMIN_PRODUIT_LOCALSTORAGE, value);
}

export function removeADMIN_PRODUIT_LOCALSTORAGE() {
    localStorage.removeItem(ADMIN_PRODUIT_LOCALSTORAGE);
}